# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-ddns
  namespace: networking
type: Opaque
stringData:
  CLOUDFLARE_EMAIL: {{ homelab_cloudflare_email }}
  CLOUDFLARE_APIKEY: {{ homelab_cloudflare_apikey }}
  CLOUDFLARE_RECORD_NAME: ipv4.{{ homelab_cloudflare_domain }}
