# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-cloud-credentials
  namespace: networking
stringData:
    email: {{ homelab_cloudflare_email }}
    api-key: {{ homelab_cloudflare_apikey }}
#
