---
- hosts: kubernetes
  become: true
  vars:
    molecule_is_test: true
    k3s_agent:
      snapshotter: native
    k3s_install_hard_links: true
  collections:
    - kilip.homelab
  roles:
    - k3s
