---
- name: Ensure configuration updated
  hosts: localhost
  tasks:
    - name: Start configuring homelab
      ansible.builtin.include_role:
        name: "kilip.homelab.generator"

- name: Base install for all nodes
  hosts: all
  gather_facts: true
  tasks:
    - name: Include base role
      ansible.builtin.include_role:
        name: "kilip.homelab.base"

- name: Install k3s on kubernetes nodes
  hosts: kubernetes
  gather_facts: true
  vars:
    molecule_is_test: true
    k3s_agent:
      node-ip: "{{ ansible_default_ipv4.address }}"
      snapshotter: native
  tasks:
    - name: Set ansible_host
      ansible.builtin.set_fact:
        ansible_host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    - name: Include k3s role
      ansible.builtin.include_role:
        name: "kilip.homelab.k3s"
