---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: node1
    image: "kilip/molecule-${MOLECULE_DISTRO:-ubuntu-20.04}:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    networks:
      - name: k3snet
  - name: node2
    image: "kilip/molecule-${MOLECULE_DISTRO:-ubuntu-20.04}:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    networks:
      - name: k3snet
  - name: node3
    image: "kilip/molecule-${MOLECULE_DISTRO:-ubuntu-20.04}:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    networks:
      - name: k3snet

provisioner:
  name: ansible
  options:
    verbose: true
  inventory:
    links:
      hosts: "sandbox/ansible/inventory/hosts"
      host_vars: "sandbox/ansible/inventory/host_vars"
      group_vars: "sandbox/ansible/inventory/group_vars"
  env:
    HOMELAB_PROJECT_DIR: "${MOLECULE_SCENARIO_DIRECTORY}/sandbox"
    SOPS_AGE_PUBLIC_KEY: "age16kqn75nkj66h0twcyf5tgzjlhr3wlvlaej0q8xwdkk4ttt0cuqgsev633a"
    SOPS_AGE_KEY_FILE: "${PWD}/etc/age.txt"
    SOPS_AGE_KEY: "AGE-SECRET-KEY-1UW0JQ4VA4PXNPDKPFHTJ932E5TVNCFMDNQKTUNCYGNUZ3VFD6E2QMQA3ZT"
  config_options:
    defaults:
      vars_plugins_enabled: "host_group_vars,community.sops.sops"
      remote_tmp: "/tmp/ansible"

verifier:
  name: ansible
