---
- name: Check sops install
  ansible.builtin.stat:
    path: "/usr/local/bin/sops"
  register: stsops

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 600

- name: Install sops release
  ansible.builtin.apt:
    deb: https://github.com/mozilla/sops/releases/download/v{{ sops_version }}/sops_{{ sops_version }}_amd64.deb
  when: not stsops.stat.exists

- name: install gnupg2
  ansible.builtin.package:
    name:
      - gnupg
      - age
    state: present
