---
- name: Gather homelab facts
  kilip.homelab.facts:

- name: Ensure sops config file exists
  ansible.builtin.template:
    src: "sops-config.yml.j2"
    dest: "{{ homelab_sops_config_file }}"
    mode: "0644"

- name: Gather existing configuration
  ansible.builtin.stat:
    path: "{{ homelab_config_file }}"
  register: scfg

- name: Verify homelab configuration
  ansible.builtin.include_tasks: verify/config.yml
  when: scfg.stat.exists

- name: Build inventory files
  ansible.builtin.include_tasks: inventory.yml
  when: scfg.stat.exists

- name: Build cluster files
  ansible.builtin.include_tasks: cluster/main.yml
  when: scfg.stat.exists
