homelab_git_repository: ENC[AES256_GCM,data:wZRObDue/u+DgK5OhSCAxa/aBuJ82NMmPrY7lDhcn0s=,iv:HjpT5ddjojYU0Kc3PFKoF4nx3zEYjSFvzQOBnVMlJK4=,tag:RAt2f8YxvDqZXvBM0Luckw==,type:str]
#ENC[AES256_GCM,data:n1CMJH77CyOB/OLbBLqfUE/7drMpAzMknSPZeG0=,iv:L7jQoQgqB81a/InV4UpTnrwz9I5SYaNHX3WgYwzb4U4=,tag:si2vEKG1z2eBjAt/YRZn5Q==,type:comment]
homelab_hosts:
    - hostname: ENC[AES256_GCM,data:fJ2y4nc=,iv:NwZPYMJFRI2AvGNR1M0/uqfP1gvuR+96EI+ljxHFhDo=,tag:OUOS+CzNCZkYH3AQNX16uw==,type:str]
      groups:
        - ENC[AES256_GCM,data:GVUxIzOwfCFghw==,iv:JKHCykfjPabquCwDKCEULKj9KyochP2zvlf0eQ5ZriQ=,tag:7EBgzhxHznJILlugG0IDKw==,type:str]
      control_node: ENC[AES256_GCM,data:qOXOVA==,iv:i48DWiGZz2iXVl2mp/8Q+P+M8cc3kLaZMc1EwBLW98A=,tag:Cg70d8kTgH7qxJSyXvjwIA==,type:bool]
      ansible_connection: ENC[AES256_GCM,data:gJr9GKaXCUJ11hceaJX5u7sY5QDYync=,iv:jlPkefYY34QBJ/PwAP6hbZ7Lc7LkUcY92isDIXY+UDg=,tag:ZLgVdTpX8xJvk6iXtXeIUg==,type:str]
    - hostname: ENC[AES256_GCM,data:Ql4M2Lw=,iv:N9fYOFyQUB2d8VeCXJjCa/IlO8VYFlVJuHYCs0eZ8KI=,tag:A4G2Ny0GPEwAcxN0ebotDw==,type:str]
      groups:
        - ENC[AES256_GCM,data:GVUxIzOwfCFghw==,iv:JKHCykfjPabquCwDKCEULKj9KyochP2zvlf0eQ5ZriQ=,tag:7EBgzhxHznJILlugG0IDKw==,type:str]
      control_node: ENC[AES256_GCM,data:z5nJ6gw=,iv:/HGzEsYdVDWJkj/FXo9+Hklp2t0hMO7EFZI5GtN0GOI=,tag:Wv7G8SuKIwqsILAKq7YooA==,type:bool]
      ansible_connection: ENC[AES256_GCM,data:2HNvonuqpgHhPL2zVPxTxrZpT/31yC0=,iv:BA0HdHOP61GB8tERSZtycYYQ3RvOr46+LfGxq1R+uvo=,tag:9aEkLzS8MxYHwMYwRUpptA==,type:str]
    - hostname: ENC[AES256_GCM,data:a8QRnoc=,iv:cNGGpf0AMSkQA4iszwm8Fn65Zk387q1RVf/uf3wuMJw=,tag:h3U5bCr29SRHgcifmCZJIA==,type:str]
      groups:
        - ENC[AES256_GCM,data:GVUxIzOwfCFghw==,iv:JKHCykfjPabquCwDKCEULKj9KyochP2zvlf0eQ5ZriQ=,tag:7EBgzhxHznJILlugG0IDKw==,type:str]
      control_node: ENC[AES256_GCM,data:z5nJ6gw=,iv:/HGzEsYdVDWJkj/FXo9+Hklp2t0hMO7EFZI5GtN0GOI=,tag:Wv7G8SuKIwqsILAKq7YooA==,type:bool]
      ansible_connection: ENC[AES256_GCM,data:td2swtnQfx3LenScxJHEXzefJkZWbb4=,iv:ICj4aT4N9iNuIWDCzd1/mTfYHDTgIKXNnI9KlkHUe5Q=,tag:wxbA0gR9ZiQph4X83q2Jmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16kqn75nkj66h0twcyf5tgzjlhr3wlvlaej0q8xwdkk4ttt0cuqgsev633a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OXhncFJpdzhGYnc4dWZT
            ek11V004Q0Uwa3JpRXNDTnBwTjBjSlJaNzI4ClZkSGswM3hQYjhJVnA1dkZWTnQv
            SGI1RTU5V0xNQVpoY3JTZFd3T1QwUjQKLS0tIDNqYXpIMndCOXgrU1VRaTlEQkMr
            QUNhVCtUTEJ3ck53Nmk3TjB4MGNCWXMKorzsShjwgigSgphd1SjAFmyUIHFmVaMU
            KHTLe50rG3hovMsE4/K67bJUsIIOi4biUyOORIC3jNJ8lGpYTRXE1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-03T14:37:35Z"
    mac: ENC[AES256_GCM,data:HL6Npb0G46NdXmqleJFiGAwLhc83M2HwTzYZsqY1FWb3dcIsXfHyIfsRQRZQcn61OKmCW9XX8LCb+1T2S9k7PZf/ynL1zczlVmTGCD06xXLgC2RIT7DJtTVGsqbd1pmgZkchLCkCPEdz5N3CzfpNiiEiP14Dnqk+BdZUmroso/8=,iv:TYppYFaKXI9t+r1aUOFPmipQweO2L6Hk3b7G44YlUuM=,tag:LVjrYVNp3uPy9MnhRwI7SQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
