name: CI

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Run CI once per day (at 05:15 UTC)
  schedule:
    - cron: '15 5 * * *'

defaults:
  run:
    working-directory: ansible_collections/kilip/homelab

env:
  PY_COLORS: 1
  ANSIBLE_FORCE_COLOR: 1

jobs:
  sanity:
    name: Sanity (${{ matrix.ansible }})
    strategy:
      fail-fast: false
      matrix:
        ansible:
          # It's important that Sanity is tested against all stable-X.Y branches
          # Testing against `devel` may fail as new tests are added.
          - stable-2.9
          - stable-2.10
          - stable-2.11
          - stable-2.12
          - stable-2.13
          - devel
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ansible_collections/kilip/homelab

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install ansible-base (${{ matrix.ansible }})
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      - name: Create default collection path symlink
        run: |
          mkdir -p /home/runner/.ansible
          ln -s /home/runner/work/ansible-collection-homelab/ansible-collection-homelab /home/runner/.ansible/collections

      - name: Install role and collection dependencies
        run: |
          ansible-galaxy install -r requirements.yml
          ansible-galaxy collection install -r requirements.yml

      - name: Run sanity tests
        run: ansible-test sanity --docker -v --color --coverage

      - name: Generate coverage report
        run: ansible-test coverage xml -v --requirements --group-by command --group-by version

      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false

  unit:
    runs-on: "ubuntu-latest"
    name: "Units (${{matrix.ansible}})"
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - stable-2.9
          - stable-2.10
          - stable-2.11
          - stable-2.12
          - stable-2.13
          - devel
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ansible_collections/kilip/homelab

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install ansible-base (${{ matrix.ansible }})
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      - name: Create default collection path symlink
        run: |
          mkdir -p /home/runner/.ansible
          ln -s /home/runner/work/ansible-collection-homelab/ansible-collection-homelab /home/runner/.ansible/collections

      - name: Install role and collection dependencies
        run: |
          ansible-galaxy install -r requirements.yml
          ansible-galaxy collection install -r requirements.yml

      # Run the unit tests
      - name: Run unit tests for all Python versions
        run: ansible-test units -v --color --docker --coverage

        # ansible-test support producing code coverage date
      - name: Generate coverage report
        run: ansible-test coverage xml -v --requirements --group-by command --group-by version

      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false

  integration:
    runs-on: ubuntu-latest
    name: Molecule (${{ matrix.scenario }}-${{ matrix.dist }})
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
          - deploy-env
          - k3s
        dist:
          - ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ansible_collections/kilip/homelab

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install test requirements
        run: pip install -r test-requirements.txt

      - name: Create default collection path symlink
        run: |
          mkdir -p /home/runner/.ansible
          ln -s /home/runner/work/ansible-collection-homelab/ansible-collection-homelab /home/runner/.ansible/collections

      - name: Install role and collection dependencies
        run: |
          ansible-galaxy install -r requirements.yml
          ansible-galaxy collection install -r requirements.yml

      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.2.0

      - name: Run molecule test
        run: molecule test -s ${{ matrix.scenario}}
        env:
          MOLECULE_DIST: ${{ matrix.dist }}
